// Codex's OTHER hook route: a plugin bundle instead of `~/.codex/hooks.json`.
//
// Writing codex's user-level hooks file does not arm it — every new or changed
// hook needs an interactive human review, persisted as a `trusted_hash`. Hooks
// that ship INSIDE a plugin skip that review ("Managed hooks are always on"),
// which is why this route exists at all.
//
// What the checkout can do, and what it deliberately cannot:
//
//  · it CAN build the bundle — a directory with `.codex-plugin/plugin.json` whose
//    `hooks` field points at a `hooks.json` in the same Claude-shaped dialect
//    codex already reads (verified against codex-cli 0.147.0: its plugin
//    validator's required fields, and its scaffold's own `"hooks": "./hooks.json"`);
//  · it CANNOT install it. A codex plugin is installed THROUGH A MARKETPLACE
//    (`codex plugin marketplace add` then `codex plugin install`), a step that is
//    the person's to run in their own host. So this generates and reports; it
//    never says the hooks are armed, and it never writes a trust hash — forging
//    one would forge somebody's security decision.

import type { HooksTemplate } from "./install-hooks.js";

/** The plugin's name, and the marker that says a bundle on disk is ours. */
export const CODEX_PLUGIN_NAME = "agent-workflow";

/** Where the bundle is generated, relative to home. */
export const CODEX_PLUGIN_DIR = [".agent-workflow", "codex-plugin"] as const;

/** `interface.category` — one of the values codex's validator accepts. */
const CATEGORY = "Productivity";

export interface CodexPluginBundle {
  /** Relative path inside the bundle → its exact bytes. */
  files: Record<string, string>;
  /** The two commands the PERSON runs; this CLI runs neither. */
  install_commands: string[];
}

/**
 * The bundle's files, built from the same template every other host adapts.
 *
 * Codex's event enum covers all five template events and its handlers admit
 * `command` AND `prompt`, so the hooks document is the template verbatim — this
 * is the one host where nothing is lost in translation, and inventing a
 * transform would only add a place for the two to disagree.
 */
export function buildCodexPluginBundle(
  template: HooksTemplate,
  version: string,
): CodexPluginBundle {
  const descriptor = {
    name: CODEX_PLUGIN_NAME,
    version: semverOrZero(version),
    description: "Workline hooks for Codex, generated by the agent-workflow CLI",
    author: { name: CODEX_PLUGIN_NAME },
    hooks: "./hooks.json",
    interface: {
      displayName: "Workline",
      shortDescription: "Workline's branch, SQL and commit guards inside Codex.",
      longDescription:
        "Ships the agent-workflow hook set as plugin-bundled hooks, so the guards run without a per-hook trust review.",
      developerName: CODEX_PLUGIN_NAME,
      category: CATEGORY,
      capabilities: [],
      defaultPrompt: "Run my Workline flow.",
    },
  };
  return {
    files: {
      ".codex-plugin/plugin.json": `${JSON.stringify(descriptor, null, 2)}\n`,
      "hooks.json": `${JSON.stringify(template, null, 2)}\n`,
    },
    install_commands: [
      "codex plugin marketplace add <bundle path>",
      `codex plugin install ${CODEX_PLUGIN_NAME}`,
    ],
  };
}

/**
 * `version` must be strict semver or codex's validator rejects the plugin.
 *
 * A version this CLI could not read comes back as `unknown`, and shipping that
 * string would produce a bundle nobody can install — with an error about the
 * version rather than about the read that failed.
 */
function semverOrZero(version: string): string {
  return /^\d+\.\d+\.\d+(?:[-+].*)?$/.test(version) ? version : "0.0.0";
}

/**
 * True when the bundle at this path is the one WE generated.
 *
 * Read from the descriptor's `name`, never from the path: a directory the person
 * put there themselves is not ours to delete because it sits where we would have
 * written.
 */
export function isOurCodexPlugin(descriptorText: string): boolean {
  try {
    const parsed = JSON.parse(descriptorText) as { name?: unknown };
    return parsed.name === CODEX_PLUGIN_NAME;
  } catch {
    return false;
  }
}
