// La publicación de un plan SELLA su baseline, dentro de la misma propuesta.
//
// El sello no puede quedar en manos de quien redacta: un digest no es algo que
// se escriba a mano, y un baseline opcional en la práctica es un baseline que se
// desincroniza. Así que lo calcula la publicación, sobre los bytes del archivo
// que el plan nombra, y lo estampa en los MISMOS bytes que se previsualizan, se
// aprueban y se escriben — una sola transición, no dos.
//
// Esto es T1.2 de F1 del plan 032.

import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { runNextNumber } from "../../src/application/dev-only-services.js";
import { resolveBoundary } from "../../src/application/flow/advance.js";
import { advanceFlow } from "../../src/application/flow/flow-service.js";
import {
  type InternalActionExecutor,
  internalActionExecutor,
} from "../../src/application/flow/internal-actions.js";
import { locateRun, readRun } from "../../src/application/flow/run-state-service.js";
import { submitFlow } from "../../src/application/flow/submit.js";
import { parsePlanBaselineSeal } from "../../src/application/parsers/spec-relation.js";
import { PathsService } from "../../src/application/paths-service.js";
import {
  type FlowDecision,
  journeyOfFlow,
  proposalContractOf,
  publishApprovalOf,
} from "../../src/domain/flow/authority.js";
import { effectApprovalDigest } from "../../src/domain/flow/authorization.js";
import type { FlowDirective } from "../../src/domain/flow/directive.js";
import { specBaselineDigest } from "../../src/domain/lineage.js";
import { normalizeNamespace } from "../../src/runtime/namespace.js";
import { FakeEnv } from "../helpers/fake-env.js";
import { RecordingGit } from "../helpers/fake-git.js";
import { NodeFileSystem } from "../helpers/real-fs.js";

const SESSION = "032-linaje-plan-new";
const CODE = "032";
const SPEC = "docs/specs/033-spec-linaje.md";
const SPEC_BYTES = `---
status: ready-for-plan
---

# Spec 033 — linaje

- S033/AC-03 — todo plan resuelve su spec a un baseline exacto.
`;

const PLAN_BYTES = `# Plan 032 — linaje

> Derived from ${SPEC} · generated by plan-new-loop
> Estado: open
> Límite de ejecución: checkout

## Origin

Spec 033.

## Tasks

### F1 — algo verificable
> Estado: pendiente
> Fuentes: workspace

- [ ] T1.1 — hacer algo _(fuentes: workspace)_

**Validación de fase:** pruebas locales sobre fixtures del checkout.

**Condición de salida:** algo es cierto.
`;

const fs = new NodeFileSystem();
const JOURNEY = journeyOfFlow("plan-new");

describe("publicar un plan sella el baseline de la spec que consumió", () => {
  let workdir: string;
  let paths: PathsService;
  let executor: InternalActionExecutor;
  /** Ruta que el reclamo real devolvió; el recorrido la fija, el test no la inventa. */
  let planPath: string | null;

  beforeEach(async () => {
    workdir = await mkdtemp(join(tmpdir(), "aw-linaje-"));
    paths = new PathsService(normalizeNamespace("agent-workflow"), workdir, workdir);
    await mkdir(join(paths.cwdSessionsDir(), SESSION), { recursive: true });
    await writeFile(
      join(paths.cwdSessionsDir(), SESSION, "SESSION.md"),
      "# SESSION — linaje\n\n## Objective\nderivar un plan\n",
      "utf8",
    );
    planPath = null;
    await mkdir(join(workdir, "docs/specs"), { recursive: true });
    await writeFile(join(workdir, SPEC), SPEC_BYTES, "utf8");
    executor = internalActionExecutor({
      fs,
      env: new FakeEnv(workdir, workdir),
      paths,
      git: new RecordingGit(),
    });
  });

  afterEach(async () => {
    await rm(workdir, { recursive: true, force: true });
  });

  async function current() {
    const read = await readRun(fs, locateRun(paths, SESSION));
    if (!read.ok) throw new Error(`esperaba leer la corrida: ${read.failure.code}`);
    return { state: read.state, resolved: resolveBoundary(read.state, JOURNEY) };
  }

  async function answer(body: unknown, approval: string | null = null): Promise<FlowDirective> {
    const result = await submitFlow(fs, paths, {
      code: CODE,
      raw: JSON.stringify(body),
      approval,
      executor,
    });
    if (!result.ok)
      throw new Error(`un rechazo de negocio viaja ok:true — ${JSON.stringify(result)}`);
    return result.directive;
  }

  /**
   * Corre de verdad el reclamo que la frontera `numbering` delega.
   *
   * El directorio y el nombre salen de la invocación SELLADA, no de una
   * constante del test: si el recorrido cambiara lo que reclama, esto reclamaría
   * lo nuevo en vez de seguir probando contra una ruta inventada.
   */
  async function claimNumber(args: readonly string[]): Promise<string> {
    const directory = args[1] as string;
    const claim = args[args.indexOf("--claim") + 1] as string;
    const out = await runNextNumber(fs, new FakeEnv(workdir, workdir), paths, {
      directory,
      claim: { name: claim, owner: SESSION },
    });
    if (out.claimed_path === null) throw new Error("el reclamo no materializó el slot");
    return relative(workdir, out.claimed_path);
  }

  /** La evidencia que una frontera de ejecución pide, con su prueba cuando la exige. */
  function validationsFor(evidence: readonly string[]): Array<Record<string, unknown>> {
    return evidence.map((id) => ({
      id,
      passed: true,
      detail: `salida de ${id}`,
      ...(id === "workline.source-bounded"
        ? {
            proof: {
              kind: "inspection" as const,
              source: "workspace",
              relative_cwd: ".",
              checkout_digest: "test-checkout",
              invocation: { artifact: "tests/unit/lineage-publication.test.ts" },
            },
          }
        : {}),
    }));
  }

  function executionBody(
    resolved: Awaited<ReturnType<typeof current>>["resolved"],
    claimed: string | null,
  ): Record<string, unknown> {
    const action = resolved.action;
    if (action === null) throw new Error("una frontera de ejecución sin invocación");
    // El reclamo del correlativo es una ESCRITURA real: el slot queda en el disco
    // con su marcador de dueño, que es lo que después le permite a la propuesta
    // completarlo sin pedir sobrescritura.
    const declared =
      claimed === null
        ? [...(resolved.proposal?.effects ?? ["read_only"])]
        : ["read_only", "local_additive"];
    return {
      input_digest: resolved.seal,
      outcome: "completed",
      invocation: action.invocation,
      validations: validationsFor(action.evidence),
      effects: { planned: [...declared], approved: [], applied: [...declared] },
      output: null,
    };
  }

  function bodyFor(
    resolved: Awaited<ReturnType<typeof current>>["resolved"],
    content: string,
    claimed: string | null = null,
  ): Record<string, unknown> {
    const stopped = resolved.stopped as FlowDecision;
    if (resolved.kind === "execution") return executionBody(resolved, claimed);
    if (resolved.kind === "semantic") {
      if (proposalContractOf(stopped) !== null) {
        if (planPath === null)
          throw new Error("se propuso guardar antes de reclamar el correlativo");
        return { input_digest: resolved.seal, artifacts: [{ path: planPath, content }] };
      }
      return { input_digest: resolved.seal, signals: [], decisions: { paso: stopped.id } };
    }
    return { input_digest: resolved.seal, choice: resolved.choices[0]?.label ?? "" };
  }

  async function answerBoundary(
    resolved: Awaited<ReturnType<typeof current>>["resolved"],
    content: string,
  ): Promise<void> {
    const stopped = resolved.stopped as FlowDecision;
    let claimed: string | null = null;
    if (stopped.id === "plan-new.numbering" && resolved.action !== null) {
      claimed = await claimNumber(resolved.action.invocation.args);
      planPath = claimed;
    }
    const directive =
      resolved.kind === "authorization"
        ? await answer(
            { input_digest: resolved.seal, choice: "Autorizar el efecto" },
            effectApprovalDigest(stopped.id, resolved.authorization?.planned ?? []),
          )
        : await answer(bodyFor(resolved, content, claimed));
    // Un rechazo viaja DENTRO de la directiva. Sin esto el walk lo re-contesta
    // hasta agotar el ledger, y el diagnóstico culpa al contador de intentos en
    // vez de a la frontera que de verdad no pasó.
    if (directive.error !== null) {
      throw new Error(`${stopped.id} rechazó: ${JSON.stringify(directive.error)}`);
    }
  }

  /** Avanza el recorrido `plan-new` hasta la confirmación del guardado. */
  async function walkToConfirmation(content = PLAN_BYTES): Promise<void> {
    const adopted = await advanceFlow(fs, paths, {
      code: CODE,
      flow: "plan-new",
      adopt: true,
      executor,
    });
    if (!adopted.ok) throw new Error("esperaba adoptar la corrida");
    for (let step = 0; step < 40; step += 1) {
      const { resolved } = await current();
      if (resolved.stopped === null) throw new Error("el recorrido terminó sin pedir confirmación");
      if (publishApprovalOf(resolved.stopped) !== null && resolved.proposal !== null) return;
      await answerBoundary(resolved, content);
    }
    throw new Error("el recorrido nunca llegó a la confirmación");
  }

  it("el plan publicado lleva su `> Baseline:` con el digest de los bytes reales de la spec", async () => {
    await walkToConfirmation();
    const gate = await current();
    await answer({ input_digest: gate.resolved.seal, choice: "Aprobar y guardar" });

    const published = await readFile(join(workdir, planPath as string), "utf8");
    expect(published).toContain(`> Baseline: ${SPEC}@${specBaselineDigest(SPEC_BYTES)}`);
    expect(parsePlanBaselineSeal(published)).toEqual({
      status: "sealed",
      baseline: { path: SPEC, number: "033", digest: specBaselineDigest(SPEC_BYTES) },
    });
  });

  it("el sello va en los bytes que la persona aprobó, no en una escritura aparte", async () => {
    await walkToConfirmation();
    const gate = await current();
    // La vista previa pesa lo que se va a escribir: el sello YA está adentro.
    const previewed = gate.resolved.proposal?.preview.find((p) => p.path === planPath);
    await answer({ input_digest: gate.resolved.seal, choice: "Aprobar y guardar" });
    const published = await readFile(join(workdir, planPath as string), "utf8");
    expect(previewed?.bytes).toBe(Buffer.byteLength(published, "utf8"));
    expect(published.length).toBeGreaterThan(PLAN_BYTES.length);
  });

  it("un plan que ya trae un sello viejo se corrige, sin duplicar la línea", async () => {
    const stale = PLAN_BYTES.replace(
      "> Estado: open",
      `> Baseline: ${SPEC}@sha256:${"a".repeat(64)}\n> Estado: open`,
    );
    await walkToConfirmation(stale);
    const gate = await current();
    await answer({ input_digest: gate.resolved.seal, choice: "Aprobar y guardar" });

    const published = await readFile(join(workdir, planPath as string), "utf8");
    const lines = published.split("\n").filter((l) => /^\s*>\s*Baseline:/i.test(l));
    expect(lines).toEqual([`> Baseline: ${SPEC}@${specBaselineDigest(SPEC_BYTES)}`]);
  });

  it("si la spec que el plan nombra no se puede leer, se publica SIN sello y no con uno inventado", async () => {
    await rm(join(workdir, SPEC));
    await walkToConfirmation();
    const gate = await current();
    await answer({ input_digest: gate.resolved.seal, choice: "Aprobar y guardar" });

    const published = await readFile(join(workdir, planPath as string), "utf8");
    expect(published).not.toMatch(/^\s*>\s*Baseline:/im);
    expect(parsePlanBaselineSeal(published)).toEqual({ status: "absent" });
  });
});
