import { execFileSync } from "node:child_process";
import { mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { GitCliAdapter } from "../../src/adapters/git-cli.js";
import { NodeFileSystem } from "../../src/adapters/node-file-system.js";
import { NodeProcess } from "../../src/adapters/node-process.js";
import { PathsService } from "../../src/application/paths-service.js";
import { prepareRetirement } from "../../src/application/retirement/prepare.js";
import type { PrepareDeps } from "../../src/application/retirement/prepare.js";
import {
  renderRetirementPreview,
  retirementPreview,
} from "../../src/application/retirement/preview.js";
import { runSessionCreate } from "../../src/application/session-create-service.js";
import type { RetirementProposal } from "../../src/domain/retirement/proposal.js";
import { normalizeNamespace } from "../../src/runtime/namespace.js";
import { FakeEnv } from "../helpers/fake-env.js";

function git(repo: string, ...args: string[]): string {
  return execFileSync("git", args, {
    cwd: repo,
    encoding: "utf-8",
    env: { ...process.env, GIT_TERMINAL_PROMPT: "0" },
  });
}

function block(sourcePath: string): string {
  return `<!-- WORKFLOW-PROJECT-START -->
## Proyecto

Retiro.

## Fuentes

| Alias | Path | Rama principal |
|---|---|---|
| acme | ${sourcePath} | main |

## Status

- Ramas de trabajo actuales:
  - acme: main
<!-- WORKFLOW-PROJECT-END -->
`;
}

const SPEC = (n: string) => `---
status: ready-for-plan
---

# Spec ${n} — algo

## Acceptance criteria

- [ ] **S${n}/AC-01 — Uno.** Algo.
`;

const PLAN = (n: string, spec: string, estado = "open") => `# Plan ${n} — algo

> Derived from docs/specs/${spec}-spec-algo.md · generated by plan-new-loop
> Estado: ${estado}

## Tasks

### F1 — hacer algo
> Estado: pendiente

- [ ] T1.1 — algo
`;

describe("retirement prepare — resolución, clausura y sello sin escribir nada", () => {
  let root: string;
  let workspace: string;
  let source: string;
  let paths: PathsService;
  let deps: PrepareDeps;
  const fs = new NodeFileSystem();

  function specFile(n: string): string {
    return `docs/specs/${n}-spec-algo.md`;
  }
  function planFile(n: string): string {
    return `docs/plans/${n}-plan-algo.md`;
  }
  function write(relative: string, content: string): void {
    writeFileSync(join(workspace, relative), content);
  }

  async function session(name: string, inputs: string[] = []): Promise<string> {
    const result = await runSessionCreate(fs, paths, {
      // El tipo sigue al sufijo del descriptor, como en los loops reales: un
      // `-quick` es una sesión quick, y es por su tipo que `quick:<NNN>` la alcanza.
      type: name.endsWith("-quick") ? "quick" : "exec",
      name,
      objetivo: "o",
      ...(inputs.length > 0 ? { inputs } : {}),
    });
    if ("error" in result) throw new Error(result.error);
    return result.sessionCreate.folder;
  }

  /** Snapshot of every path under the workspace, to prove `prepare` writes nothing. */
  function tree(dir = workspace, prefix = ""): string[] {
    const out: string[] = [];
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const rel = `${prefix}${entry.name}`;
      out.push(rel);
      if (entry.isDirectory()) out.push(...tree(join(dir, entry.name), `${rel}/`));
    }
    return out.sort();
  }

  beforeEach(() => {
    root = mkdtempSync(join(tmpdir(), "retire-"));
    workspace = join(root, "ws");
    source = join(root, "acme");
    mkdirSync(join(workspace, "docs", "specs"), { recursive: true });
    mkdirSync(join(workspace, "docs", "plans"), { recursive: true });
    mkdirSync(join(workspace, ".workflow", "sessions"), { recursive: true });
    mkdirSync(source, { recursive: true });
    git(source, "init", "--initial-branch=main");
    git(source, "config", "user.email", "t@example.com");
    git(source, "config", "user.name", "T");
    writeFileSync(join(source, "README.md"), "hola\n");
    git(source, "add", "-A");
    git(source, "commit", "-m", "inicial");

    write("CLAUDE.md", block(source));
    const env = new FakeEnv(join(root, "home"), workspace);
    paths = new PathsService(normalizeNamespace("workflow"), join(root, "home"), workspace);
    deps = { fs, env, git: new GitCliAdapter(new NodeProcess()), paths };
  });
  afterEach(() => rmSync(root, { recursive: true, force: true }));

  async function prepare(mode: "discard" | "reset", target: string) {
    return prepareRetirement(deps, { mode, target });
  }

  function proposalOf(outcome: Awaited<ReturnType<typeof prepare>>): RetirementProposal {
    if (!outcome.ok) throw new Error(`rechazo inesperado: ${outcome.rejection.message}`);
    return outcome.proposal;
  }

  it("acepta cada clase de objetivo: cualificado, ruta, carpeta y quick", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    const exec = await session("algo-plan-exec", [planFile("024")]);
    const quick = await session("suelto-quick");

    expect(proposalOf(await prepare("discard", "spec:025")).target).toEqual({
      kind: "spec",
      key: "025",
    });
    expect(proposalOf(await prepare("discard", "plan:024")).target).toEqual({
      kind: "plan",
      key: "024",
    });
    expect(proposalOf(await prepare("discard", planFile("024"))).target).toEqual({
      kind: "plan",
      key: "024",
    });
    expect(proposalOf(await prepare("discard", `session:${exec}`)).target).toEqual({
      kind: "session",
      key: exec,
    });
    // `quick:<NNN>` alcanza una sesión quick por su número, no por su carpeta.
    expect(proposalOf(await prepare("discard", `quick:${quick.slice(0, 3)}`)).target).toEqual({
      kind: "session",
      key: quick,
    });
  });

  it("rechaza un número abreviado que coincide con más de un nodo", async () => {
    write(specFile("024"), SPEC("024"));
    write(planFile("024"), PLAN("024", "024"));

    const outcome = await prepare("discard", "024");
    expect(outcome.ok).toBe(false);
    if (outcome.ok) return;
    expect(outcome.rejection.code).toBe("TARGET_AMBIGUOUS");
    expect(outcome.rejection.candidates).toEqual(expect.arrayContaining(["spec:024", "plan:024"]));
  });

  it("resuelve un número abreviado cuando sólo un nodo responde", async () => {
    write(planFile("024"), PLAN("024", "099"));
    expect(proposalOf(await prepare("discard", "24")).target).toEqual({
      kind: "plan",
      key: "024",
    });
  });

  it("descarta una spec con toda su descendencia transitiva y en orden de retiro", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    const refine = await session("algo-spec-refine", [specFile("025")]);
    const exec = await session("algo-plan-exec", [planFile("024")]);

    const proposal = proposalOf(await prepare("discard", "spec:025"));
    const closure = proposal.closure.map((c) => `${c.node.kind}:${c.node.key}`);
    // Las sesiones salen antes que los documentos, y la spec objetivo al final:
    // ningún lector intermedio ve una sesión apuntando a un documento que ya no está.
    // Entre sesiones el orden es su identidad, que es estable entre corridas.
    expect(closure).toEqual([`session:${refine}`, `session:${exec}`, "plan:024", "spec:025"]);
    expect(proposal.deletes.map((d) => d.path)).toEqual(
      expect.arrayContaining([specFile("025"), planFile("024")]),
    );
    // Un discard nunca restaura: lo que el objetivo recibió se va con él.
    expect(proposal.restores).toEqual([]);
  });

  it("bloquea cuando un descendiente también pertenece a algo fuera del alcance", async () => {
    write(specFile("025"), SPEC("025"));
    write(specFile("026"), SPEC("026"));
    write(planFile("024"), PLAN("024", "025"));
    // Una sesión que declara DOS padres: uno dentro del alcance y otro fuera.
    await session("compartida-plan-exec", [planFile("024"), specFile("026")]);

    const outcome = await prepare("discard", "spec:025");
    expect(outcome.ok).toBe(false);
    if (outcome.ok) return;
    expect(outcome.rejection.code).toBe("SHARED_CONSUMER");
    expect(outcome.rejection.candidates).toContain("spec:026");
  });

  it("bloquea cuando un descendiente sólo tiene procedencia en prosa", async () => {
    write(specFile("025"), SPEC("025"));
    // Una sesión legacy: carpeta a mano, sin custodia, con su Origin en prosa.
    const folder = "090-legacy-spec-refine";
    mkdirSync(join(workspace, ".workflow", "sessions", folder), { recursive: true });
    writeFileSync(
      join(workspace, ".workflow", "sessions", folder, "SESSION.md"),
      `# SESSION — ${folder}\n\n## Origin\n- desde docs/specs/025-spec-algo.md\n`,
    );

    const outcome = await prepare("discard", "spec:025");
    expect(outcome.ok).toBe(false);
    if (outcome.ok) return;
    expect(outcome.rejection.code).toBe("EVIDENCE_MISSING");
    expect(outcome.rejection.candidates.join(" ")).toContain(folder);
  });

  it("resetea una ejecución parcial devolviendo el plan a sus bytes previos", async () => {
    write(specFile("025"), SPEC("025"));
    const before = PLAN("024", "025");
    write(planFile("024"), before);
    const exec = await session("algo-plan-exec", [planFile("024")]);
    // La sesión avanzó el plan: marcó una tarea y puso la fase en ejecución.
    write(planFile("024"), before.replace("- [ ] T1.1", "- [x] T1.1"));

    const proposal = proposalOf(await prepare("reset", planFile("024")));
    expect(proposal.mode).toBe("reset");
    expect(proposal.target).toEqual({ kind: "session", key: exec });
    const restore = proposal.restores.find((r) => r.path === planFile("024"));
    expect(restore?.existed).toBe(true);
    expect(restore?.content).toBe(before);
    // El plan cambió desde el baseline, y eso es exactamente lo que el preview avisa.
    expect(restore?.current_digest).not.toBe(restore?.digest);
    // La carpeta de la sesión se va; el plan NO figura como borrado.
    expect(proposal.deletes.map((d) => d.path)).toEqual([`.workflow/sessions/${exec}`]);
    expect(retirementPreview(proposal).restores).toEqual([
      { path: planFile("024"), to: "bytes-previos", changed_since: true },
    ]);
  });

  it("resetea una sesión cerrada pero inconclusa: `.closed` no es convergencia", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    const exec = await session("algo-plan-exec", [planFile("024")]);
    writeFileSync(join(workspace, ".workflow", "sessions", exec, ".closed"), "");

    expect(proposalOf(await prepare("reset", `session:${exec}`)).target).toEqual({
      kind: "session",
      key: exec,
    });
  });

  it("se niega a resetear una sesión cuyo artefacto ya llegó a done", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    const exec = await session("algo-plan-exec", [planFile("024")]);
    // El plan cerró: la sesión que lo llevó ahí no vuelve a ser incompleta por selección.
    write(planFile("024"), PLAN("024", "025", "done").replace("### F1", "### F1"));

    const outcome = await prepare("reset", `session:${exec}`);
    expect(outcome.ok).toBe(false);
    if (outcome.ok) return;
    expect(outcome.rejection.code).toBe("RESET_SESSION_CONVERGED");
  });

  it("pide la sesión exacta cuando un plan tiene dos sesiones incompletas", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    const a = await session("uno-plan-exec", [planFile("024")]);
    const b = await session("dos-plan-refine", [planFile("024")]);

    const outcome = await prepare("reset", planFile("024"));
    expect(outcome.ok).toBe(false);
    if (outcome.ok) return;
    expect(outcome.rejection.code).toBe("RESET_AMBIGUOUS_SESSION");
    expect(outcome.rejection.candidates).toEqual(expect.arrayContaining([a, b]));
  });

  it("resetea un quick sin artefacto base retirando sólo su sesión", async () => {
    const quick = await session("suelto-quick");
    const proposal = proposalOf(await prepare("reset", `session:${quick}`));
    expect(proposal.restores).toEqual([]);
    expect(proposal.deletes).toEqual([
      { path: `.workflow/sessions/${quick}`, kind: "directory", digest: null },
    ]);
    expect(proposal.event.command).toBe("reset");
  });

  it("declara una custodia VACÍA antes de aplicar, sin prometer una restauración", async () => {
    // El estado real de toda sesión nacida por el protocolo antes de este arreglo:
    // custodia sellada, cero artefactos. `reset` sobre ella no restaura nada.
    const quick = await session("suelto-quick");

    const proposal = proposalOf(await prepare("reset", `session:${quick}`));
    expect(proposal.custody).toEqual([{ session: quick, declared: 0, restored: 0 }]);
    expect(proposal.restores).toEqual([]);
    // La única huella durable tampoco insinúa un rollback que no ocurrió.
    expect(proposal.event.summary).toBe(`retirada session:${quick} sin restaurar ningún artefacto`);

    const preview = retirementPreview(proposal);
    expect(preview.restores_nothing).toBe(true);
    expect(preview.custody).toEqual([{ session: quick, declared: 0, restored: 0 }]);

    const human = renderRetirementPreview(preview);
    // Dicho ANTES de aplicar y fuera de toda sección: una sección vacía se omite,
    // y esta advertencia no puede depender de un encabezado que no se imprime.
    expect(human).toContain("Nada vuelve atrás");
    expect(human).toContain(`${quick}: sin artefactos declarados`);
  });

  it("distingue una custodia CON artefactos y dice cuántos vuelven atrás", async () => {
    write(specFile("025"), SPEC("025"));
    const before = PLAN("024", "025");
    write(planFile("024"), before);
    const exec = await session("algo-plan-exec", [planFile("024")]);
    write(planFile("024"), before.replace("- [ ] T1.1", "- [x] T1.1"));

    const proposal = proposalOf(await prepare("reset", `session:${exec}`));
    expect(proposal.custody).toEqual([{ session: exec, declared: 1, restored: 1 }]);

    const preview = retirementPreview(proposal);
    expect(preview.restores_nothing).toBe(false);
    const human = renderRetirementPreview(preview);
    expect(human).toContain(`${exec}: 1 artefacto(s) declarados, 1 vuelve(n) atrás`);
    expect(human).not.toContain("Nada vuelve atrás");
  });

  it("un discard declara lo custodiado sin hablar de restaurar: nunca restaura", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    const exec = await session("algo-plan-exec", [planFile("024")]);

    const proposal = proposalOf(await prepare("discard", "plan:024"));
    expect(proposal.custody).toEqual([{ session: exec, declared: 1, restored: 0 }]);

    const human = renderRetirementPreview(retirementPreview(proposal));
    expect(human).toContain(`${exec}: 1 artefacto(s) declarados`);
    // `restores_nothing` es cierto para TODO discard, así que anunciarlo sería
    // ruido: un discard nunca prometió devolver nada.
    expect(human).not.toContain("Nada vuelve atrás");
  });

  it("el rechazo por falta de custodia nombra el registro ausente, no una fecha de nacimiento", async () => {
    // Una carpeta hecha a mano HOY: es la ausencia del archivo lo único que se
    // verificó, y de una ausencia no se deduce cuándo nació la sesión.
    const folder = "090-hecha-a-mano-plan-exec";
    mkdirSync(join(workspace, ".workflow", "sessions", folder), { recursive: true });
    writeFileSync(
      join(workspace, ".workflow", "sessions", folder, "SESSION.md"),
      `# SESSION — ${folder}\n`,
    );

    const outcome = await prepare("reset", `session:${folder}`);
    expect(outcome.ok).toBe(false);
    if (outcome.ok) return;
    expect(outcome.rejection.code).toBe("EVIDENCE_MISSING");
    expect(outcome.rejection.message).toContain("no hay registro de custodia");
    expect(outcome.rejection.message).toContain(".custody.json");
    // Y ofrece la salida en vez de dejar al usuario adivinando.
    expect(outcome.rejection.action).toContain("aw discard");
    const said = `${outcome.rejection.message} ${outcome.rejection.action}`;
    expect(said).not.toMatch(/naci|antes de que|legacy/i);
  });

  it("no escribe nada: ni sesión, ni journal, ni archivo, ni ref", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    await session("algo-plan-exec", [planFile("024")]);
    const beforeTree = tree();
    const beforeRefs = git(source, "show-ref");

    await prepare("discard", "spec:025");
    await prepare("reset", planFile("024"));

    expect(tree()).toEqual(beforeTree);
    expect(git(source, "show-ref")).toBe(beforeRefs);
  });

  it("sella el mismo digest para el mismo inventario y otro cuando algo material cambia", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    await session("algo-plan-exec", [planFile("024")]);

    const first = proposalOf(await prepare("discard", "spec:025"));
    const again = proposalOf(await prepare("discard", "spec:025"));
    expect(again.digest).toBe(first.digest);

    // Un documento del alcance cambia: el sello ya no es el mismo, así que la
    // aprobación anterior deja de servir.
    write(planFile("024"), `${PLAN("024", "025")}\n<!-- una línea más -->\n`);
    const third = proposalOf(await prepare("discard", "spec:025"));
    expect(third.digest).not.toBe(first.digest);
  });

  it("deriva el preview del objeto sellado, sin volver a leer el workspace", async () => {
    write(specFile("025"), SPEC("025"));
    write(planFile("024"), PLAN("024", "025"));
    const exec = await session("algo-plan-exec", [planFile("024")]);

    const proposal = proposalOf(await prepare("discard", "spec:025"));
    const preview = retirementPreview(proposal);
    expect(preview.digest).toBe(proposal.digest);
    expect(preview.target).toBe("spec:025");
    expect(preview.disappears.map((d) => d.node)).toEqual([
      `session:${exec}`,
      "plan:024",
      "spec:025",
    ]);
    expect(preview.history_row).toContain("discard · spec:025");
    expect(preview.touches_git_history).toBe(false);
  });

  it("la vista humana dice lo mismo que el JSON y omite las secciones vacías", async () => {
    write(specFile("025"), SPEC("025"));
    const before = PLAN("024", "025");
    write(planFile("024"), before);
    const exec = await session("algo-plan-exec", [planFile("024")]);
    write(planFile("024"), before.replace("- [ ] T1.1", "- [x] T1.1"));

    const proposal = proposalOf(await prepare("reset", planFile("024")));
    const human = renderRetirementPreview(retirementPreview(proposal));

    // El mismo alcance y el mismo digest que el JSON: un host de terminal y un
    // host de agente pueden diferir en formato, nunca en qué se va a retirar.
    expect(human).toContain(`Restaurar session:${exec}`);
    expect(human).toContain(`Digest de aprobación: ${proposal.digest}`);
    expect(human).toContain(`${planFile("024")} → bytes-previos (cambió desde el baseline)`);
    expect(human).toContain(`.workflow/sessions/${exec}`);
    expect(human).toContain("Huella en HISTORY:");
    // Nada de "reverts: ninguno": una sección sin contenido no se imprime, para
    // que la que importa —un revert— no quede sepultada entre encabezados vacíos.
    expect(human).not.toContain("Commits que se revierten");
    expect(human).not.toContain("Unidades que se reconcilian");
  });
});
