/**
 * A hub with a long history and one pending item of each common class, in MemFs.
 *
 * It exists for the size rules of `status`: an output that must not grow with the
 * hub's history is only proved against a hub that has one, and against the same
 * hub with more of it. Every history file is dated before the pending ones, so
 * adding more history never moves `last_activity`.
 */

import { PathsService } from "../../src/application/paths-service.js";
import type { CliContext } from "../../src/cli/types.js";
import { normalizeNamespace } from "../../src/runtime/namespace.js";
import { FakeEnv } from "./fake-env.js";
import { MemFs } from "./mem-fs.js";

/** The open plan the gates judge, and the specs still owed. */
export const LARGE_HUB_OPEN_PLAN = "087";
export const LARGE_HUB_UNREFINED_SPEC = "090";
export const LARGE_HUB_UNPLANNED_SPEC = "091";

/** Enough closed plans that adding a hundred more does not change a count's width. */
export const LARGE_HUB_CLOSED_PLANS = 150;

const HISTORY_DATE = new Date(2026, 0, 10, 9, 0, 0);
const PENDING_DATE = new Date(2026, 5, 20, 9, 0, 0);

export function largeHubPaths(): PathsService {
  return new PathsService(normalizeNamespace("workflow"), "/home", "/cwd");
}

/** What `status` reads from its context: the board needs no git and no process. */
export function largeHubContext(fs: MemFs): CliContext {
  return {
    fs,
    env: new FakeEnv("/home", "/cwd"),
    paths: largeHubPaths(),
  } as unknown as CliContext;
}

export function largeHub(): MemFs {
  const fs = new MemFs();
  fs.file(
    "/cwd/CLAUDE.md",
    "<!-- WORKFLOW-HUB-START -->\n## Hub\nhub-grande\n<!-- WORKFLOW-HUB-END -->\n",
  );
  addClosedPlans(fs, 100, LARGE_HUB_CLOSED_PLANS);
  for (let n = 1; n <= 120; n += 1) closedSession(fs, n);
  fs.file(
    "/cwd/.workflow/sessions/121-descartes-plan-exec/SESSION.md",
    "# SESSION — descartes\n\n## Objective\nDescartar\n\n## Type\nexec\n",
    HISTORY_DATE,
  );
  fs.file(
    "/cwd/.workflow/sessions/121-descartes-plan-exec/BACKLOG.md",
    "# BACKLOG\n\n## Deferred\n- soporte XP: baja prioridad\n- soporte ARM: baja prioridad\n",
    HISTORY_DATE,
  );
  fs.file("/cwd/.workflow/sessions/121-descartes-plan-exec/.closed", "", HISTORY_DATE);
  fs.file(
    `/cwd/docs/plans/${LARGE_HUB_OPEN_PLAN}-plan-abierto.md`,
    [
      `# Plan ${LARGE_HUB_OPEN_PLAN} — abierto`,
      "",
      "> Standalone: prueba · generated by plan-new-loop",
      "> Estado: open",
      "",
      "## Tasks",
      "",
      "### F1 — hecho",
      "> Estado: validada",
      "> Fuentes: hub",
      "",
      "- [x] T1.1 — hecho",
      "",
      "### F2 — pendiente",
      "> Estado: bloqueada",
      "> Bloqueo: falta la fixture",
      "> Fuentes: hub",
      "",
      "- [ ] T2.1 — pendiente",
      "",
    ].join("\n"),
    PENDING_DATE,
  );
  fs.file(
    `/cwd/docs/specs/${LARGE_HUB_UNREFINED_SPEC}-spec-borrador.md`,
    "---\nstatus: draft\n---\n# Spec borrador\n\n## Open questions\n- ¿qué pasa con XP?\n",
    PENDING_DATE,
  );
  fs.file(
    `/cwd/docs/specs/${LARGE_HUB_UNPLANNED_SPEC}-spec-lista.md`,
    "---\nstatus: ready-for-plan\n---\n# Spec lista\n\n## Open questions\nNone\n",
    PENDING_DATE,
  );
  return fs;
}

/** Closed plans `from..from+count-1`, all dated before anything pending. */
export function addClosedPlans(fs: MemFs, from: number, count: number): void {
  for (let n = from; n < from + count; n += 1) {
    fs.file(
      `/cwd/docs/plans/${String(n).padStart(3, "0")}-plan-cerrado-${n}.md`,
      [
        `# Plan ${n} — cerrado-${n}`,
        "",
        "> Standalone: prueba · generated by plan-new-loop",
        "> Estado: done",
        "> Cierre: sesión 001 · 2026-01-10",
        "> Assurance: verified",
        "",
        "## Tasks",
        "",
        "### F1 — hecho",
        "> Estado: validada",
        "> Fuentes: hub",
        "",
        "- [x] T1.1 — hecho",
        "",
      ].join("\n"),
      HISTORY_DATE,
    );
  }
}

function closedSession(fs: MemFs, n: number): void {
  const folder = `/cwd/.workflow/sessions/${String(n).padStart(3, "0")}-cerrada-${n}-quick`;
  fs.file(
    `${folder}/SESSION.md`,
    `# SESSION — cerrada-${n}\n\n## Objective\nHecho\n\n## Type\nquick\n`,
    HISTORY_DATE,
  );
  fs.file(`${folder}/.closed`, "", HISTORY_DATE);
}
