/**
 * The base journey every v11 run was written against: the one 25.6.1 walked.
 *
 * A v11 file carries no provenance of its own, and 25.6.1 refused any v11 cursor
 * that did not match exactly this list, so it is the only journey an open v11 run
 * can stand on. The upgrade to v12 records it as the run's `journey_base`; from
 * then on each run carries the journey of the build that last aligned it.
 * `tests/unit/flow-journey-compat.test.ts` pins it to the frozen 25.6.1 fixture.
 */
import type { WorklineFlow } from "../../application/capability/compose.js";

export const V11_JOURNEY_BASE: Readonly<Record<WorklineFlow, readonly string[]>> = {
  quick: [
    "chassis.docs-boundary",
    "chassis.route-evaluation",
    "chassis.research-exhaustion",
    "quick.entry-gate-signal",
    "quick.entry-size-gate",
    "quick.anti-duplicate",
    "quick.gate-choice",
    "quick.session-create",
    "quick.success-criteria-authoring",
    "quick.success-criteria-ratification",
    "quick.artifact-seed-order",
    "quick.branch-precondition",
    "quick.fix-preview",
    "quick.fix-preview-approval",
    "quick.deliverable-authoring",
    "quick.db-touched",
    "quick.db-scripts-only",
    "quick.growth-escalation",
    "quick.escalation-destination",
    "quick.convergence-gate",
    "quick.review-precedence",
    "quick.review-findings",
    "quick.commit-authorization",
    "chassis.finalize",
  ],
  "spec-refine": [
    "chassis.docs-boundary",
    "chassis.route-evaluation",
    "chassis.research-exhaustion",
    "spec-refine.session",
    "spec-refine.escalation-adoption",
    "spec-refine.baseline-scope",
    "spec-refine.change-shape-gate",
    "spec-refine.split-signal",
    "spec-refine.split-gate",
    "spec-refine.split-choice",
    "spec-refine.gap-recognition",
    "spec-refine.gap-destination",
    "spec-refine.ideation-trigger",
    "spec-refine.ideation-consent",
    "spec-refine.content-authoring",
    "spec-refine.functional-ambiguity",
    "spec-refine.design-reuse",
    "spec-refine.design-publication",
    "spec-refine.ready-gate",
    "spec-refine.save-proposal",
    "spec-refine.save-confirmation",
    "spec-refine.publication",
    "chassis.finalize",
  ],
  "plan-new": [
    "chassis.docs-boundary",
    "chassis.route-evaluation",
    "chassis.research-exhaustion",
    "plan-new.spec-readiness",
    "plan-new.session",
    "plan-new.slug-derivation",
    "plan-new.numbering",
    "plan-new.phase-shaping",
    "plan-new.batch-eligibility-signal",
    "plan-new.batch-inference",
    "plan-new.batch-isolation",
    "plan-new.split-signal",
    "plan-new.split-gate",
    "plan-new.split-choice",
    "plan-new.coherence-gate",
    "plan-new.save-proposal",
    "plan-new.save-confirmation",
    "plan-new.publication",
    "plan-new.adoption",
    "chassis.finalize",
  ],
  "plan-refine": [
    "chassis.docs-boundary",
    "chassis.route-evaluation",
    "chassis.research-exhaustion",
    "plan-refine.session",
    "plan-refine.escalation-adoption",
    "plan-refine.journey-map",
    "plan-refine.preserve-validated",
    "plan-refine.batch-eligibility-signal",
    "plan-refine.batch-reinference",
    "plan-refine.batch-isolation",
    "plan-refine.split-signal",
    "plan-refine.executability-gate",
    "plan-refine.split-in-place",
    "plan-refine.save-proposal",
    "plan-refine.save-confirmation",
    "plan-refine.publication",
    "chassis.finalize",
  ],
  "plan-exec": [
    "chassis.docs-boundary",
    "chassis.route-evaluation",
    "chassis.research-exhaustion",
    "plan-exec.session",
    "plan-exec.entry-gate",
    "plan-exec.entry-gap-recognition",
    "plan-exec.entry-gap-severity",
    "plan-exec.normalization-consent",
    "plan-exec.source-scope",
    "plan-exec.batch-eligibility-signal",
    "plan-exec.batch-inference",
    "plan-exec.batch-isolation",
    "plan-exec.design-precondition",
    "plan-exec.unit-acquisition",
    "plan-exec.branch-precondition",
    "plan-exec.implementation",
    "plan-exec.deviation-recognition",
    "plan-exec.deviation-eligibility",
    "plan-exec.deviation-gate",
    "plan-exec.escalation-package",
    "plan-exec.validation-execution",
    "plan-exec.deferred-check",
    "plan-exec.review-findings",
    "plan-exec.batch-close",
    "plan-exec.settlement-authoring",
    "plan-exec.settlement-question",
    "plan-exec.settlement-publication",
    "plan-exec.final-validation",
    "plan-exec.commit-enablement",
    "plan-exec.commit-authorization",
    "plan-exec.commit-execution",
    "plan-exec.unit-integration",
    "plan-exec.plan-done",
    "chassis.finalize",
  ],
};
